steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/container-app/container1:${COMMIT_SHA}', '.']
    dir: 'container1'
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/container-app/container1:${COMMIT_SHA}']
  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'us-central1-docker.pkg.dev/${PROJECT_ID}/container-app/container1:${COMMIT_SHA}', 'us-central1-docker.pkg.dev/${PROJECT_ID}/container-app/container1:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/container-app/container1:latest']
  # Update deployment if the cluster exists
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/container1', 'container1=us-central1-docker.pkg.dev/${PROJECT_ID}/container-app/container1:${COMMIT_SHA}']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=saikat-cluster'
