apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: us-central1-docker.pkg.dev/container-app-454314/container-app/container1:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: saikat-volume
          mountPath: /saikat_PV_dir
        env:
        - name: CONTAINER2_URL
          value: "http://container2-service:5001"
      volumes:
      - name: saikat-volume
        persistentVolumeClaim:
          claimName: saikat-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  selector:
    app: container1
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
